LOCAL_PATH := device/oukitel/c18pro

BOARD_HAS_MTK_HARDWARE := true
MTK_HARDWARE := true


TARGET_ARCH := arm64
TARGET_CPU_ABI := arm64-v8a
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_VARIANT := generic
TARGET_CPU_CORTEX_A53 := true

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic

TARGET_USES_64_BIT_BINDER := true


TARGET_BOARD_PLATFORM := mt6757
TARGET_BOOTLOADER_BOARD_NAME := k57pv1_dm_64
TARGET_NO_BOOTLOADER := true

BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_TAGS_OFFSET := 0x12f88000
BOARD_BOOTIMG_HEADER_VERSION := 2
BOARD_RAMDISK_OFFSET := 0x11f88000
BOARD_MKBOOTIMG_ARGS += --kernel_offset 0x00008000
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)

TARGET_PREBUILT_KERNEL := device/oukitel/c18pro/prebuilt/Image.gz
TARGET_RECOVERY_FSTAB := device/oukitel/c18pro/recovery.fstab

BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb

# Storages
BOARD_HAS_NO_MISC_PARTITION := true
TW_DEFAULT_EXTERNAL_STORAGE := true
TW_INTERNAL_STORAGE_PATH := "/sdcard"
TW_INTERNAL_STORAGE_MOUNT_POINT := "sdcard"
TW_EXTERNAL_STORAGE_PATH := "/extSdCard"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "extSdCard"
TW_FLASH_FROM_STORAGE := true
TW_SDEXT_NO_EXT4 := true
RECOVERY_SDCARD_ON_DATA := true
BOARD_HAS_LARGE_FILESYSTEM := true

BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 33554432
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 3221225472
BOARD_CACHEIMAGE_PARTITION_SIZE := 452984832
BOARD_USERDATAIMAGE_PARTITION_SIZE := 3221225472

BOARD_FLASH_BLOCK_SIZE := 131072

TW_EXCLUDE_SUPERSU := true

TW_THEME := portrait_hdpi

TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
TW_MAX_BRIGHTNESS := 255
TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_ID := true
TW_INCLUDE_CRYPTO := true

TARGET_USERIMAGES_USE_EXT4 := true

# TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/class/android_usb/android0/f_mass_storage/lun/file
# maybe don't exist on device, idk :3

TW_BRIGHTNESS_PATH := /sys/class/leds/lcd-backlight/brightness

SHRP_DEVICE_CODE := c18pro
SHRP_PATH := device/oukitel/$(SHRP_DEVICE_CODE)
SHRP_MAINTAINER := MyNameIsKitsune
SHRP_REC := /dev/block/bootdevice/by-name/recovery
SHRP_DARK := true
		

